version: '3.8'
services:
  sample-service:
    image: amitkshirsagar13/sample-service:24
    ports:
      - "8080:80"
    environment:
      - VPORT=8085
      - PORT=8090
    # volumes: 
    #   - "D:/local/sample-service/:/tmp/sample-service"
    dns:
      - 192.168.1.111
      - 8.8.8.8
    extra_hosts:
      - "sample-service:127.0.0.1"
    hostname: sample-service-host
    networks:
      sample-service-network: {}
    deploy:
      replicas: 2
      resources:
        limits:
          cpus: '0.5'
          memory: 512M
        reservations:
          cpus: '0.2'
          memory: 256M

networks:
  sample-service-network:
    driver: overlay
    attachable: true
    ipam:
      driver: default
      config:
        - subnet: 172.16.238.0/24
          gateway: 172.16.238.1
