version: '3.6'
services:
  sample-service:
    image: amitkshirsagar13/sample-service:24
    ports:
      - "8080:80"
    environment:
      - VPORT=8085
      - PORT=8090
    volumes: 
      - "D:/local/sample-service/:/tmp/sample-service"
    deploy:
      replicas: 1
      resources:
        limits:
          cpus: '0.5'
          memory: 512M
        reservations:
          cpus: '0.2'
          memory: 256M